usr/share/xfce4/backdrops/Campos_de_Castilla_by_David_Arias_Gutierrez.jpg usr/share/xfce4/backdrops
usr/share/xfce4/backdrops/Lighthouse_by_Dominik_Czernetzky.jpg usr/share/xfce4/backdrops
usr/share/xfce4/backdrops/Sunset_by_Kacperu.jpg usr/share/xfce4/backdrops
usr/share/xfce4/backdrops/Untitled_by_Anna_Ceccarelli.jpg usr/share/xfce4/backdrops
usr/share/xfce4/backdrops/Untitled_by_Luna_Reichmann.jpg usr/share/xfce4/backdrops
usr/share/xfce4/backdrops/Untitled_by_Nesimi_Acarca.jpg usr/share/xfce4/backdrops